<Project>
    <PropertyGroup>
        <Authors>Mark van Leijenhorst</Authors>
        <Company>Droomploeg</Company>
        <Product>Droomploeg Postbode</Product>
        <Copyright>© 2024 Droomploeg. Licensed under the GNU AGPL v3.0</Copyright>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Droomploeg/Postbode</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Droomploeg/Postbode</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>azure;servicebus;blazor;dotnet;operations;dlq</PackageTags>
    </PropertyGroup>
</Project>