<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Channels\**" />
    <EmbeddedResource Remove="Channels\**" />
    <None Remove="Channels\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.12.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Droomploeg.DreamOps.Application\Droomploeg.DreamOps.Application.csproj" />
    <ProjectReference Include="..\Droomploeg.DreamOps.Core\Droomploeg.DreamOps.Domain.csproj" />
  </ItemGroup>

</Project>
